#LAB 1- vlan creation + Access port
[switches] 
SW1 access_port=FastEthernet0/1 vlan_id=10 vlan_name=SALES
SW2 access_port=FastEthernet0/1 vlan_id=20 vlan_name=HR

[switches:vars]
ansible_connection=local



