- name: this is ansible playbook
  hosts: switches
  gather_facts: no

  vars:
    secure_ports:
      - "FastEthernet0/1"
      - "FastEthernet0/2"
      - "FastEthernet0/3"

  tasks:
    - name: port security config
      copy:
        content: |
          {% for port in secure_ports %}
          interface {{ port }}
           switchport mode access
           switchport port-security
           switchport port-security maximum 1
           switchport port-security violation shutdown
           switchport port-security mac-address sticky
           no shutdown
          {% endfor %}
        dest: "./configs/{{ inventory_hostname }}_port_security.cfg"
