- name: OSPF Configuration
  hosts: routers
  gather_facts: no

  vars:
    networks:
      R1:
        - { net: "10.0.0.0", wildcard: "0.0.0.3" }
        - { net: "192.168.10.0", wildcard: "0.0.0.255" }
        - { net: "192.168.20.0", wildcard: "0.0.0.255" }
      R2:
        - { net: "10.0.0.0", wildcard: "0.0.0.3" }
        - { net: "172.16.1.0", wildcard: "0.0.0.255" }

  tasks:
    - name: Generate OSPF routing config
      copy:
        content: |
          router ospf 1
           router-id {{ router_id }}
          {% for n in networks[inventory_hostname] %}
           network {{ n.net }} {{ n.wildcard }} area 0
          {% endfor %}
        dest: "./configs/{{ inventory_hostname }}_ospf.cfg"
